### ISSUE TITLE
A master wall_edit view and template

### ISSUE THREAD

**Issue by Loisel** [jakubfabian/topo#22]
I suggest a wall_edit view and template that replaces the current route_edit.
wall_edit should provide the following functionality:
- Show a list of routes (clickable) on the spot.
  - with a `add route` button and optional `edit route` and `delete route` visible to spot managers.
  - routes in the list that are associated to the current wall via a intermediate RouteGeometry are highlighted somehow.
- A box showing the route details of the currently selected route (or some of them).
- A leaflet widget showing the routes on the wall.
  - When a route is selected in the list and the route exists on the wall, the route is made editable.
  - When the route is selected in the leaflet, the route is made editable and is selected in the list.
  - When a route is selected in the list that does not correspond to a `RouteGeometry`, the leaflet allows to draw the route and save the geometry.
- A form to edit the other wall properties.

This view replaces the route edit view in the current form. For route_edit I suggest a simple model form that edits only the route properties. Similarly, route_add would create an empty route and redirects to route edit (again, the `RouteGeometry` will not be touched).

**Comment by jakubfabian** [comment]
![img_20160323_104844](https://cloud.githubusercontent.com/assets/11333567/13981685/d43a28c4-f0e5-11e5-9687-3228c66abd47.jpg)
Click on the image to see it not upside down....

I would like to have this list editing tool that enables the user to move routes from a list of spot routes to here assigned wall routes.

Not as interactive as you imagine it but good for a first working version because simpler:
Workflow:
- open wall edit
- we will have already routes associated with this wall or none so far -- anyway, these will be in the right box
- all the routes a spot has (excluding the ones in the right box) will be in the left box
- the available routes should be sorted by walls with unassigned ones in a extra slot
- you then move routes that you want to have in this wall back and forth
- when satisfied, click a button or maybe update list below interactively with ajax controls
- have a list with associated routes and a button to edit geometry
- click edit to change routegeometry in leaflet

the lower two items already worked in ``route_edit''
This should be OK to implement and gives a first working solution.

**Comment by jakubfabian** [comment]
Note to myself...
  look at something like this for the back and forth list merger ... http://jsfiddle.net/82q72xk9/43/

**Comment by Loisel** [comment]
Still missing: some **grouping** of the routes in the routepool on a spot, preferable by wall association.

**Comment by jakubfabian** [comment]
make it a table like in excel with name, associated wall, grade, first 
ascent, so that one can click on the table header and sort it differently?

**Comment by jakubfabian** [comment]
Done, for the most part -- still has issues but we should probably open new issues for that as the key idea changed quite a bit from this earlier draft.
