### ISSUE TITLE
Grading System

### ISSUE THREAD

**Issue by Loisel** [jakubfabian/topo#37]
Implement a nice way to select the grading of a route.

Thoughts:
- Use choices, not "write what you want charfields".
- Probably integer fields so that one can calculate something.
- Narrow choices down to a grading system, otherwise list is very long.
- Implement grading system on a spot level? Or are there spots with different grading systems for different walls? If so, is this rare?
- If we make a quantization of difficulty to meet the fine-graining of all grading systems we can just implement labels for the choices in each grading system and we could easily switch the grading system. This was what I had in mind when I defined the grading system on the spot level.

Any ideas?

**Comment by datenhahn** [comment]
How about that:

Allow users to input every type of grade (one number, one gradetype select), set a default on spot level, but always display the "native grade" (the grade type the user put into it) first. Have an automatic conversion of grades when the user selects a different representation (in "viewing" mode).

**Comment by jakubfabian** [comment]
I would like to have just one field.

As it is now it is simple to have it displayed and also compute mean 
values etc.

If we need to have a stripped down interface when creating new routes on 
a spot, we can just limit the form in the template or maybe even the 
forms.py allows that.

In the latter case, just do that like the way you did it earlier.... but 
with a single choices field in the model?

I love the idea that the model knows about possible choices rather than 
have a generic int....

**Comment by jakubfabian** [comment]
Auto conversion between grades is difficult.... they do not really compare well

**Comment by Loisel** [comment]
Ok. What about this: We define a `Grade` on the model with a `grade_system` field. Then we can add a model choice field that uses a queryset

```
spot.route_set.filter(grade_system=spot.grade_system)
```

in the template. What do you think?

**Comment by jakubfabian** [comment]
Grade is now model choice field and RouteForms are filtered according to the spots grading system.
I consider that done.
