### ISSUE TITLE
Parking

### ISSUE THREAD

**Issue by Loisel** [jakubfabian/topo#38]
I suggest to add the parking locations to the model. We add a description text field and a geometry field.
Pro:
- many-to-many with spots

Cons:
- additional work

**Comment by jakubfabian** [comment]
Thumbs up.

Same for generic labels and bolts on walls etc.

I thought about maybe making a derived model(if thats possible) for 
gimmicki stuff that can be put additionally on maps...

So that you can pack it in a view as generic item , give it to the 
template and the templating engine knows which icon they should have.

Need to check if thats feasible within django....

**Comment by Loisel** [comment]
I agree. On the map level we might also like to have accommodations or climbing shops and the like... 

Well we could pack a list in views: item is [(queryset, icon), ] for querysets that support queryset.geom and on the template just iterate over the list and add them as collections.
For editing it is more complicated but probably it would be worth writing an interface :P Some auto-generated map-decoration toolbox.

**Comment by jakubfabian** [comment]
Given that this should be considered with the already referenced generic map decorations I close this issue
